# Generated by Django 5.0.6 on 2024-06-09 19:32

import django.utils.timezone
import mailing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': [('can_view_email', 'Can view email')], 'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_edit_mailing_status', 'Can edit mailing status')], 'verbose_name': 'mailing', 'verbose_name_plural': 'mailings'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='mailing_end',
            field=models.DateTimeField(default=mailing.models.one_week_from_now, verbose_name='end_timestamp'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='mailing_sent',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='send_timestamp'),
        ),
    ]
