# Generated by Django 5.0.6 on 2024-06-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_edit_title', 'Can edit blog title'), ('can_edit_content', 'Can edit blog content')], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
